title: 은평구 노동자종합지원센터
languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true

disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - xml

params:
  homeText: You just made a Hugo blog from scratch.