---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: homepage/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: homepage/content/workshops
  label: Workshops
  create: all
  match: "**/*"
- type: directory
  path: homepage/content/consulting
  label: Consulting
  create: all
  match: "**/*"
- type: directory
  path: homepage/content/allim
  label: Allim
  create: all
  match: "**/*"
- type: directory
  path: homepage/content/about
  label: About
  create: all
  match: "**/*"
upload_dir: homepage//static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: homepage
  instant_preview_command: cd homepage && hugo server -D -E -F --port 8080 --bind
    0.0.0.0 --renderToDisk -d public
version: 0.71.1
