backend:
  name: git-gateway
  branch: master
  # name: test-repo

media_folder: "homepage/static/uploads" 
public_folder: "/uploads" 

collections:
  - label: "설정"
    name: "settings"
    files:
      - name: "basic"
        label: "기본 정보"
        file: "homepage/data/eplabor.yml"
        fields:
          - {label: "법인명", name: "title", widget: "string"}
          - {label: "태그라인", name: "tagline", widget: "string"}
          - {label: "전화번호", name: "tel", widget: "string"}
          - {label: "팩스", name: "fax", widget: "string"}
          - {label: "이메일", name: "email", widget: "string"}
          - {label: "대표자", name: "representative", widget: "string"}
          - {label: "주소", name: "location", widget: "string"}
          - {label: "푸터", name: "footer", widget: "markdown"}
      - name: "front"
        label: "홈페이지"
        file: "homepage/data/front.yml"
        fields:
          - label: "슬라이드"
            name: "slides"
            widget: "list"
            fields:
              - {label: "슬라이드 제목", name: "title", widget: "string"}
              - {label: "슬라이드 설명글", name: "description", widget: "string"}
              - {label: "슬라이드 배경이미지", name: "bg", widget: "image"}
              - {label: "슬라이드 버튼 텍스트", name: "btn_text", widget: "string"}
              - {label: "슬라이드 버튼 링크", name: "btn_url", widget: "string"}
          - label: "센터 정보 블록"
            name: "center_info"
            widget: "list"
            fields:
              - {label: "제목", name: "title", widget: "string"}
              - {label: "아이콘", name: "icon", widget: "string"}
              - {label: "링크", name: "url", widget: "string"}
          - label: "최신 글 3개"
            description: "3개 넘어도 3개만 출력합니다."
            name: "recents"
            widget: "list"
            fields:
              - {label: "아이콘", name: "icon", widget: "string"}
              - {label: "제목", name: "title", widget: "string"}
              - {label: "게시판 유형", name: "type", widget: "string"}
          - label: "홍보용 4개 패널"
            name: "four_panes"
            description: "4개 넘어도 4개만 출력합니다."
            widget: "list"
            fields:
              - {label: "제목1", name: "text1", widget: "string"}
              - {label: "제목2", name: "text2", widget: "string"}
              - {label: "배경 이미지", name: "bg", widget: "image"}
              - {label: "링크", name: "url", widget: "string"}
          - label: "사진 절반 글 절반"
            name: "halfhalfs"
            widget: "list"
            fields:
              - {label: "사진", name: "photo_url", widget: "image"}
              - {label: "사진 위치", name: "photo_left", widget: "boolean", hint: "선택하면 왼쪽, 아니면 오른쪽"}
              - {label: "링크", name: "message_url", widget: "string"}
              - {label: "제목", name: "message_title", widget: "text"}
              - {label: "설명", name: "message_description", widget: "text"}
  - label: "센터소개"
    name: "about"
    folder: "homepage/content/about/"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
  - label: "공지사항"
    name: "notices"
    folder: "homepage/content/allim/notices"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
  - label: "센터소식"
    name: "news"
    folder: "homepage/content/allim/news"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
  - label: "자료실"
    name: "downloads"
    folder: "homepage/content/allim/downloads"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
  - label: "발간자료"
    name: "publications"
    folder: "homepage/content/allim/publications"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
  - label: "교육신청"
    name: "workshops"
    folder: "homepage/content/workshops"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
  - label: "노동상담"
    name: "consulting"
    files:
      - label: "이용안내"
        name: "consulting-info"
        file: "homepage/content/consulting/info.md"
        fields:
          - {label: "제목", name: "title", widget: "string"}
          - {label: "작성일", name: "date", widget: "datetime"}
          - {label: "본문", name: "body", widget: "markdown"}
  - label: "주요사례"
    name: "consulting-references"
    folder: "homepage/data/faqs/"
    extension: "yml"
    fields:
      - label: "근로계약"
        name: "contract"
        widget: "list"
        file: "homepage/data/faqs/contract.yml"
        fields:
          - {label: "분류", name: "category", widget: "string"}
          - {label: "제목", name: "title", widget: "string"}
          - {label: "본문", name: "body", widget: "markdown"}
      - label: "근로시간/휴일/휴가"
        name: "restday"
        widget: "list"
        file: "homepage/data/faqs/restday.yml"
        fields:
          - {label: "분류", name: "category", widget: "string"}
          - {label: "제목", name: "title", widget: "string"}
          - {label: "본문", name: "body", widget: "markdown"}
      - label: "체불임금"
        name: "wages"
        widget: "list"
        file: "homepage/data/faqs/wages.yml"
        fields:
          - {label: "분류", name: "category", widget: "string"}
          - {label: "제목", name: "title", widget: "string"}
          - {label: "본문", name: "body", widget: "markdown"}
      - label: "해고"
        name: "layoff"
        widget: "list"
        file: "homepage/data/faqs/layoff.yml"
        fields:
          - {label: "분류", name: "category", widget: "string"}
          - {label: "제목", name: "title", widget: "string"}
          - {label: "본문", name: "body", widget: "markdown"}
      - label: "폭행/성희롱"
        name: "sexual"
        widget: "list"
        file: "homepage/data/faqs/sexual.yml"
        fields:
          - {label: "분류", name: "category", widget: "string"}
          - {label: "제목", name: "title", widget: "string"}
          - {label: "본문", name: "body", widget: "markdown"}
      - label: "실업급여/4대보험"
        name: "unemployment"
        widget: "list"
        file: "homepage/data/faqs/unemployment.yml"
        fields:
          - {label: "분류", name: "category", widget: "string"}
          - {label: "제목", name: "title", widget: "string"}
          - {label: "본문", name: "body", widget: "markdown"}
      - label: "산업재해"
        name: "accidents"
        widget: "list"
        file: "homepage/data/faqs/accidents.yml"
        fields:
          - {label: "분류", name: "category", widget: "string"}
          - {label: "제목", name: "title", widget: "string"}
          - {label: "본문", name: "body", widget: "markdown"}
      - label: "참고서식"
        name: "form"
        widget: "list"
        file: "homepage/data/faqs/form.yml"
        fields:
          - {label: "분류", name: "category", widget: "string"}
          - {label: "제목", name: "title", widget: "string"}
          - {label: "본문", name: "body", widget: "markdown"}
